### PR TITLE
App strings reworked

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by albancrommer** [comment]
Ouch. We should have connected about this. 

Every change needs to be forwarded to source code javascript.

Example for the string "Creating account...": 

https://github.com/inklewriter/freeinklewriter/blob/dev/app/assets/javascripts/inklewriter-write.js#L9042

I guess a script to walk over the code and sed your way in should work.

**Comment by albancrommer** [comment]
@comradekingu for the sake of simplicity I am going to close this pull request.

I have imported your branch into the repository togethder with source code changes as commit #3c4e872 and will merge into dev branch once I've checked it works fine. 

Thanks a lot for your work!

**Comment by comradekingu** [comment]
@albancrommer 
Curiously the "connected about" part (with the link) I think was what sent your original message to my spam.
Sorry to have fallen off the ball here. If there is anything else I can do let me know :)

**Comment by albancrommer** [comment]
hey @comradekingu thanks for your feedback.

I've ported the strings into the app, except for a few who seemed to lost contextual information.
Now I need to add a country/language selector to the frontend + cookie management.
Then we should be ready to deliver.

On your end, maybe you could help us with weblate's configuration?
 I've added an english file to use as a base, but I'm lost in the weblate's UI...

**Comment by comradekingu** [comment]
@albancrommer 
I added `public/translations/dictionary.en.json` for monolingual basefile in https://hosted.weblate.org/settings/inklewriter/inklewriter-frontend/#files 
And the error went away. Not sure if it will come back.
Translations are now empty…
I'll add my nb_NO translation if it doesn't auto-populate.

https://github.com/inklewriter/freeinklewriter/pull/56 would help.

**Comment by albancrommer** [comment]
Hum.

Tried to push an empty commit, but that didn't fix it in weblate. 

It's just as I feared, it got lost in the source file switch. 

I fear to have to recreate the frontend project...

**Comment by comradekingu** [comment]
@albancrommer 
The files are still there in the dev branch.
Somehow what I did creates en_EN at the bottom of each file, instead of adding to what is already there.
https://github.com/inklewriter/freeinklewriter/blob/c3ac27245b2e03b98a436d9e98566e579c4cb8b2/public/translations/dictionary.nb_no.json#L167

Removing that setting should revert to where it picks up two "en" locales, but then I don't know why…

**Comment by albancrommer** [comment]
Nice catch. 

It's a change I made that might explains the behaviour you describe and the the disappearing of other languages.

DE and nl_NO JSON files shared the same unique dictionary key than the fr file : "fr_FR". 

But of course, that couldn't work, so I've reworked these main keys. Thus losing the translations.

And now the system expects a "en_EN" key for all translation dictionaries, and adds it automatically.

That means we have to figure out the best option. 

* Remove that main key in dictionaries? It is redundant.

* Figure out a way to tell weblate that "dictionary.es.json" has all translations strings under a "es" key?

**Pull request closed without merging**
